### ISSUE TITLE
Could not find the config file

### ISSUE THREAD

**Issue by lubianat** [tabdelaal/scRNAseq_Benchmark#1]
Hello! 

I read your bioRxiv paper and was interested in taking a look at your snakemake pipeline. 

I could not fInd your config file, though, and running snakemake yields this error: 

 KeyError in line 17 ./scRNAseq_Benchmark/Snakefile:
'tools_to_run'

Is it available somewhere?

Thanks,
Tiago

**Comment by hailiangmei** [comment]
Hi Tiago,

An example of config file is described in the README: https://github.com/tabdelaal/scRNAseq_Benchmark/tree/snakemake_and_docker#the-config-file

Could you create this file and try to run the snakefile again?

Thanks for your interest in our work!

Cheers,
Leon

**Comment by lubianat** [comment]
Oh, ok, thanks!

I am a bit lost with the branching system, though. 

The config information is in the snakemake_and_docker branch README. 
However, the General Usage information is only available in the master branch README. 

Aggregating the information in a single branch could make it easier for other users. 

Thanks again,
Cheers,
Tiago

**Comment by lubianat** [comment]
Hey, me again. 

I manage to work my way around it up to a point, thanks. 
I am not an expert on docker/singularity, and I'm bumping into the following error:


Failed to pull singularity image from docker://scrnaseqbenchmark/cross_validation:latest: 
FATAL:   While making image from oci registry: failed to get checksum for docker://scrnaseqbenchmark/cross_val│
idation:latest: error getting username and password: error reading JSON file 


Do you know how to solve it? Or even better, do you know any resource/tutorial where I can learn to avoid this kind of issue (either here or in the README)? 
I just want to know enough to be able to reproduce your pipeline. 

Thanks,
Tiago

**Comment by DavyCats** [comment]
Hi Tiago,
The general usage described on the master branch relates to running the scripts manually. If you want to use the Snakemake workflow, the snakemake_and_docker branch README is where you should be looking. I can see that this might be confusing :/

Regarding the error you're getting, could you share the snakemake command and version of singularity you are using? I haven't seen this error before, personally.
