### ISSUE TITLE
Python imports in baseline container

### ISSUE THREAD

**Issue by concatenize** [tabdelaal/scRNAseq_Benchmark#10]
You've been more than helpful already, so I am sorry to keep bothering, but I have come across one more bug that I just cannot figure out. It only manifested this afternoon -- prior to that, everything was going pretty well, even past this step. The problem is with a python module import when running one of your scripts in the corresponding container. To reproduce it, try this:

```
$ singularity shell docker://scrnaseqbenchmark/baseline:latest
Singularity> python3 
>>> from sklearn import linear_model
```

I get this error. 

```
/usr/local/lib/python3.5/dist-packages/scipy/__init__.py:115: UserWarning: Numpy 1.13.3 or above is required for this version of scipy (detected version 1.10.1)
  UserWarning)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "rank_gene_dropouts.py", line 8, in <module>
    from sklearn import linear_model
  File "/usr/local/lib/python3.5/dist-packages/sklearn/__init__.py", line 76, in <module>
    from .base import clone
  File "/usr/local/lib/python3.5/dist-packages/sklearn/base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "/usr/local/lib/python3.5/dist-packages/sklearn/utils/__init__.py", line 13, in <module>
    from scipy.sparse import issparse
  File "/usr/local/lib/python3.5/dist-packages/scipy/sparse/__init__.py", line 230, in <module>
    from .csr import *
  File "/usr/local/lib/python3.5/dist-packages/scipy/sparse/csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: numpy.core.multiarray failed to import
```

I am completely stumped -- running an import command inside of a container should be the definition of reproducible; what could either of use possibly do differently? If you have any ideas, I am happy to send any info you need.

**Comment by DavyCats** [comment]
Could you try running this again but using this command to enter the container instead:
```
singularity shell --containall docker://scrnaseqbenchmark/baseline:latest
```

Singularity by default mounts some directories of the host machine. This might be the cause of the problem, though I can't say for sure.  Using the `--containall` flag will disable this behaviour and the container should become fully self-contained (just like it would be if run with docker).

**Comment by concatenize** [comment]
That works! Thank you! When invoking snakemake, I will add that to `--singularity-args`.
