### ISSUE TITLE
Fix MemoryError

### ISSUE THREAD

**Issue by paula-tataru** [tabdelaal/scRNAseq_Benchmark#13]
Hi,

I have a rather big dataset and the python scripts fail while loading the data (I have tried this for `rank_gene_dropouts.py` and `run_SVM.py`) with:
```
numpy.core._exceptions.MemoryError: Unable to allocate array with shape (58184, 11261) and data type float64
```

I have successfully fixed the issue by asking pandas to read the file in chunks. I have also applied the log transformation while reading the chunks. 

This is how the reading the data looks like for these two python files:
`rank_gene_dropouts.py`:
- Current
```
# read the data
data = pd.read_csv(DataPath,index_col=0,sep=',')
data = data.iloc[tokeep]
data = np.log2(data+1)
```
- Updated
```
# read the data
data = pd.DataFrame()
for chunk in pd.read_csv(DataPath, index_col=0, sep=',', chunksize=1000):
    data = pd.concat([data, np.log2(chunk+1)], ignore_index=True)
data = data.iloc[tokeep]
```

`run_SVM.py`:
- Current (I have skipped the irrelevant lines that were in between)
```
# read the data
data = pd.read_csv(DataPath,index_col=0,sep=',')
data = data.iloc[tokeep]
# normalize data
data = np.log1p(data)
```
- Updated
```
# read and normalize the data
data = pd.DataFrame()
for chunk in pd.read_csv(DataPath, index_col=0, sep=',', chunksize=1000):
    data = pd.concat([data, np.log1p(chunk)], ignore_index=True)
data = data.iloc[tokeep]
```

It might be a good idea to update the python scripts to better handle bigger datasets.

**Comment by tabdelaal** [comment]
Hi, sorry for the late reply and thanks for the valuable suggestion. With more work, we also learned that reading csv file is way more difficult than reading other formats like pkl or h5/h5ad. If you load your file once, you may save it in one of these formats and python can easily read these files after this one time.
