### ISSUE TITLE
Ask for help on python based package installation

### ISSUE THREAD

**Issue by chenziyi** [tabdelaal/scRNAseq_Benchmark#14]
I want to valid the result according to the data you provided. However, these python based packages including: DigitalCellSorter, Cell_BLAST, moana was depending on different version of pythooon and some other python packages. Could you please help on how to install them on my own computer. Do you install them with conda? which version was used for all three packages? Or, could you please provide the installation scripts for me? Thanks

**Comment by lcmmichielsen** [comment]
Sorry for the late reply! We ran all the python tools using python v3.6. It might be that in the mean time the methods were updated, so this might explain the problem. In table 1 in the paper you can find the versions of the methods we used. To install methods, we always followed the explanation on the Github. At that time, however, there was no package for CellBLAST yet, so we downloaded the cellblast python scripts and ran those.
