### ISSUE TITLE
Train in one data and test on the another one

### ISSUE THREAD

**Issue by FADHLyemen** [tabdelaal/scRNAseq_Benchmark#15]
Great work your cell identification paper.
So how to use 
run_scPred('~/TM/Filtered_TM_data.csv','~/TM/Labels.csv','~/TM/CV_folds.RData','~/Results/TM/')
If I need to test the algorithm in Separate training and testing dataset. The same thing you did in your manuscript 
Training in one platform and test on the other.

**Comment by crotoc** [comment]
I am trying to figure out as well. It seems to not be included in this repo. Please help us!

**Comment by crotoc** [comment]
I may understand how to do it:
1. Combine the train data and test data. Rowname is cell barcode and colname is gene
2. Create a 1-col file with label of train data.
3. Create a RData include several variables:  
a. Cells_to_Keep: length is equal to cell numbers
b. col_Index: 1
c. n_folds: 2
d. Train_Idx: a list including the line number of training cells
e. Test_Idx: a list including the line number of testing cells
4. Run cmd.

**Comment by lcmmichielsen** [comment]
Sorry for the late reply. This is indeed how it works! You can also find some cross-dataset examples at the zenodo (https://zenodo.org/record/3357167#.YV1V5PlBx3g), so you can use those as a guideline.

**Comment by crotoc** [comment]
Can you help confirm some details? I only want to train 1 dataset and test 1 dataset. 

A. Cells_to_Keep should include all cells in the combined data.
B. col_Idex should be 1
C. n_fold is 2 or 1 ??
D. Train_Idx should be a list containing only one vector of the training data. (Examples of your dataset contain 2 right now because you need to do training and test reversely)
E. Text_Idx should be a list containing only one vector of the test data as well. 

Please help me check whether I am correct? Thanks!

**Comment by lcmmichielsen** [comment]
A. Yes
B. Yes. col_index refers to the column you want to read from your labels.csv file, so if you only have 1 column, this should be 1 (or 0 depending on whether you use python or R).
C. This depends whether you want to test both directions (e.g. train on 1 and test on 2, train on 2 and test on 1 -> 2 folds) or only one direction (train on 1 and test on 2 -> 1 fold
D/E. The train_idx and test_idx are both a list containing vector. The number of vectors  depends on whether you want to test both directions. If you test 1 direction you only need 1 vector, if you test both directions you will need 2.

Hope this helps!

**Comment by crotoc** [comment]
Very clear! Thanks for your explanation! Appreciate your great work that save me a lot of time!

**Comment by crotoc** [comment]
One more question! When doing only one direction, how many lines of label I should put in label csv? In both direction it's equal to the sum of training and testing.

**Comment by crotoc** [comment]
I figured out that the label length must be equal to the total cell number of training and test or it threw an error. Thanks!
