### ISSUE TITLE
Paper's results: Data for Median F1 Accuracy vs Time?

### ISSUE THREAD

**Issue by Firedrops** [tabdelaal/scRNAseq_Benchmark#16]
Hi, I am looking for a scatter plot of the Median F1 Accuracy vs the Computation Time of each method on a common dataset, perhaps Zheng sorted or 68k.

I could not find either the plot nor a table of the actual computation values in the paper and supplementary figures. The closest was Supplementary Figure S13, which was a plot of computation time vs no. of cells.

Just wondering if this information is available anywhere? Or, if not, you would be able to provide it?

**Comment by lcmmichielsen** [comment]
Hi! In this file: [timevsmedF1.csv](https://github.com/tabdelaal/scRNAseq_Benchmark/files/7291968/timevsmedF1.csv), you can find the running time & median F1 score per classifier per number of cells (scale). Scale is the percentage of cells of the TM dataset used, which corresponds to 463, 2,280, 4,553, 9,099, 22,737, and 45,469 cells respectively. Hope this helps.
