### ISSUE TITLE
scPred dockerfile version of scPred and other installation

### ISSUE THREAD

**Issue by xyfan1030** [tabdelaal/scRNAseq_Benchmark#17]
I want to valid the result of scPred, and I am using the newest version of scPred(1.9.2), however, it didn't work and the Rstudio told me that I didn't have several functions which is related to scPred including eigenDecompose. So I want to know which version of scPred should be used and other config file of this baseline!

**Comment by tabdelaal** [comment]
Hi, sorry for the late reply. I recall that I had to fork the scPred github to make a minor edit while working on the benchmark study. You can refer to this github (https://github.com/tabdelaal/scPred) which contains the forked version we used.
