### ISSUE TITLE
Zheng et al. sorted data

### ISSUE THREAD

**Issue by mbernste** [tabdelaal/scRNAseq_Benchmark#3]
Hi, In your paper, it mentions that the Zheng et al. sorted PBMC data was subsampled down to 2k cells per cell type. I am wondering if the data (or cell barcodes) for these subsampled cells are provided or can be provided. I do not see this dataset on the Zenodo repository.

Thanks!
Matt

**Comment by ahmedmahfouz** [comment]
This dataset was not included at the time we put out the preprint and that is why it is not present in the old Zenodo dataset. We have now added the new Zenodo link with the final datasets used in the published version of the paper to GitHub.
