### ISSUE TITLE
Running benchmarking pipeline without Singularity

### ISSUE THREAD

**Issue by joycekang** [tabdelaal/scRNAseq_Benchmark#4]
Hello! Thanks so much for making your code so well-documented and accessible. I'm interested in benchmarking a new cell type identification tool using your snakemake pipeline, but our computing cluster is having issues getting singularity installed. Is there a way to run the comparison tests without using singularity?

**Comment by DavyCats** [comment]
Currently, the only way to run the pipeline is by using singularity. You might be able to run it without the `--use-singularity` flag if all the tools are installed on your system, though I haven't tried this.

You could also use conda to run it, but this will require you to [add the `conda` field to all the rules](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management). Unfortunately, many of the tools have not been made available on conda, so this will only work for a subset.
