### ISSUE TITLE
Missing rank_genes_dropouts.csv

### ISSUE THREAD

**Issue by concatenize** [tabdelaal/scRNAseq_Benchmark#7]
Hi all,

Very nice work on this project, and I really enjoyed your "one rule to rule them all" allusion! I am having an issue with the gene ranking. Details are attached. Is there a way to either 1) get the gene ranking to work or 2) bypass it, since I am using all genes anyway?

Thank you!

P.S. Details. I am using this command with these snake- and config files, and I get this error log. I am running it from the `Snakemake/` subdirectory, because I tried running it from the root and then it cannot find the snakefile.

` snakemake --configfile config.yml --use-singularity`

[Snakefile.txt](https://github.com/tabdelaal/scRNAseq_Benchmark/files/4162396/Snakefile.txt)

[config.yml.txt](https://github.com/tabdelaal/scRNAseq_Benchmark/files/4162397/config.yml.txt)

[error.log](https://github.com/tabdelaal/scRNAseq_Benchmark/files/4162436/error.log)

**Comment by concatenize** [comment]
I also get text printed to the terminal, but not in the error log:

`/bin/sh: syntax error: unterminated quoted string`

When I change the rule for gene-ranking to start with " echo GRAAAAAHH || ", I see GRAAAAAHH printed to the terminal, and the unterminated string error goes away. Instead, I see the error `bash: Results/test: No such file or directory`. But I know the pipeline can find my results folder, because it has placed `CV_folds.RData` there.

**Comment by concatenize** [comment]
Based on many other tests, I think that bash commands in Singularity are probably running in the wrong working directory, but I have been unable to verify this because commands like "echo $PWD" produce no output (or blank output?). Do you have a recommendation for how to debug this?

**Comment by concatenize** [comment]
I have also tried many variations of the Singularity "bind points"/"bind mounts"/"bind paths", including exactly what you suggest (as far as I am able to correctly fill in the blanks). Can you explain what the bracketed terms mean here?
```
snakemake \
  --configfile <configfile> \
  --use-singularity \
  --singularity-args '--bind <location of inputs>:<location of inputs> --bind <output directory>:<output directory>'
```

**Comment by DavyCats** [comment]
Hi @concatenize,

In your config.yml.txt you are referring to the inputs using relative paths. The scripts are probably unable to reach that directory as it is not mounted in the container. Indeed using the command you posted in your last message should help resolve this. The bracketed terms should be replaced with the absolute paths to the directories. For example:
```bash
snakemake \
  --configfile config.yml.txt \
  --use-singularity \
  --singularity-args '--bind /my/folder/:/my/folder --bind /my/folder/scRNAseq_Benchmark/Snakemake/Results:/my/folder/scRNAseq_Benchmark/Snakemake/Results'
```
In this case the second bind is probably not neccessary.

As for the "unterminated quoted string" error, I was unable to reproduce this error. Could you try removing this line from that rule:
`"echo test > {wildcards.output_dir}/test\n"`
And see if the errors remain? This line was just there for testing, it doesn't actually do anything important (and is only there because I forgot to remove it :roll_eyes:).

I hope this helps. If not, let me know!

**Comment by concatenize** [comment]
Thanks for the quick response! I got rid of the "unterminated quoted string" error, but I am still having problems with gene ranking. 

Here is my current config file:

```
output_dir: /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results
datafile:   /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark_datasets/Inter-dataset/Brain/MouseV1_HumanMTG/MouseV1_HumanMTG.csv
labfile:    /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark_datasets/Inter-dataset/Brain/MouseV1_HumanMTG/MouseV1_HumanMTG_Labels34.csv
human: true
tools_to_run: 
- singleCellNet
- SVM
```

Here is the current snakefile.

[Snakefile.txt](https://github.com/tabdelaal/scRNAseq_Benchmark/files/4165514/Snakefile.txt)

And the error I am receiving.

```
singularity_arguments='bash -c set -euo pipefail;  python3 rank_gene_dropouts.py  /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark_datasets/Inter-dataset/Brain/MouseV1_HumanMTG/MouseV1_HumanMTG.csv  /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/CV_folds.RData  /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results  &> /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/rank_genes_dropouts.log'
singularity_binds='|TXcWug:/Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark_datasets|xWWByP:/Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results|dJBAek:/mnt/snakemake|home:/Users/concatenize'
bash: /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/rank_genes_dropouts.log: No such file or directory
[    4.730810] reboot: Power down
Waiting at most 5 seconds for missing files.
MissingOutputException in line 65 of /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Snakefile:
Missing files after 5 seconds:
/Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/rank_genes_dropouts.csv
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/.snakemake/log/2020-02-06T090700.964709.snakemake.log
```

This is difficult to follow up on because `rank_genes_dropouts.log` is blank -- the gene ranking script produces no output at all. Should I insert some print statements to see where `rank_gene_dropouts.py` gets stuck?

**Comment by DavyCats** [comment]
```
bash: /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/rank_genes_dropouts.log: No such file or directory
```
This line suggests that the Results directory does not exist. Was `rank_genes_dropouts.log` created during the last run? Because that error sounds to me like the rule failed before it even ran the script, as it could not create the log file to write the stdout/stderr to.

Could you try running it with a completely cleared outputs folder and with the following command:
```bash
snakemake \
  --configfile config.yml.txt \
  --use-singularity \
  --singularity-args '--bind /Users/concatenize/Desktop/scRNA_data_analysis/:/Users/concatenize/Desktop/scRNA_data_analysis/'
```

**Comment by concatenize** [comment]
> This line suggests that the Results directory does not exist.

No, it exists.

>  Was rank_genes_dropouts.log created during the last run? 

Yes. 

> Could you try running it with a completely cleared outputs folder and with the following command?

Yes. This produces a new error: CV_folds.Rdata is missing, and CV_folds.log is created, but it is empty, and there is a bash error claiming that it does not exist. Full log attached.

[new_log.txt](https://github.com/tabdelaal/scRNAseq_Benchmark/files/4165635/new_log.txt)

**Comment by concatenize** [comment]
I see the bash error is not in the log. It says:

`bash: /Users/concatenize/Desktop/scRNA_data_analysis/scRNAseq_Benchmark/Snakemake/Results/CV_folds.log: No such file or directory`

Could this mean there is still an issue with the singularity bind point?

**Comment by DavyCats** [comment]
It really sounds like there is something wrong with the binding of the output directory.

Snakemake itself is creating those log files, hence why you are seeing them, but they can't be accessed (or created) from within the singularity container. 

Which version of singularity are you using? I remember that there were some issues with binding to paths that didn't exist inside the container with versions of singularity before 3.0.0

**Comment by concatenize** [comment]
Sorry for the delay -- I had to go to a meeting. I am using singularity version `3.3.0-rc.1.658.g7427b73f1.dirty` on Mac OS 10.14.6. 

Can I bind path X/Y/Z on my computer to a path A/B/C that is guaranteed to exist within the container? Then change my config to A/B/C/whatever.csv ? If so, then:

- in the singularity args, is it `--bind A/B/C/:X/Y/Z` or `--bind X/Y/Z:A/B/C/`?
- what is an example of a path that is guaranteed to be accessible within the container?

I am sorry -- I am totally new to Singularity, and I thought it would solve these cross-platform issues, but it's never easy, so I will do some reading and try to work this out.

**Comment by concatenize** [comment]
How does singularity find your containers? It seems you call snakemake, and then snakemake sees the `use-singularity` flag. In most snakemake rules, then there is a `singularity` key whose value looks like `"docker://scrnaseqbenchmark/baseline:{}".format(dockerTag)`, where the top of the snakefile sets `dockerTag = "latest" #FIXME tagged versions`. 

How does snakemake then infer that it needs to look in `Dockerfiles/baseline`? Is it possible that the snakemake is not finding the containers?

UPDATE: tried editing to `"docker://Dockerfiles/baseline:{}".format(dockerTag)`; this errs very fast with `Failed to pull singularity image from docker://Dockerfiles/baseline:latest:`. So, I think it was fine. I'll need to find the issue elsewhere.

**Comment by concatenize** [comment]
Reading about singularity, it seems that only Linux is supported. (e.g. in the [user guide](https://singularity.lbl.gov/user-guide), it says "Mobility of compute is defined as the ability to define, create and maintain a workflow and be confident that the workflow can be executed on different ... operating systems (as long as it is Linux)." Sort of like the [Model T!](http://oplaunch.com/blog/2015/04/30/the-truth-about-any-color-so-long-as-it-is-black/)) Singularity's preferences aside, your Dockerfiles are also full of apt-get commands. I'm using a Mac, so maybe I should just move all the code to a Linux machine and try it there.

**Comment by concatenize** [comment]
It is working now on a Linux machine that we have in the lab. You may want to list Linux as an explicit requirement for your snakemake pipeline.

**Comment by DavyCats** [comment]
Ah, I didn't realize singularity didn't support Mac OS (although I guess that makes sense since it uses a different kernel). I will add a note about this, thanks for letting us know!

Regarding the containers. Docker images are actually prebuilt and saved online. In this case at docker hub (https://hub.docker.com/u/scrnaseqbenchmark), though there are other repositories that can be used as well (eg. quay.io). Singularity never touches the dockerfiles. These are uploaded to docker hub and then used by docker hub to build the images. Docker and singularity will then pull this image from the repository when you want to use it (and it will cache it, so it won't have to pull it every time).

**Comment by concatenize** [comment]
Ooh, good to know. I will need to follow up on that info about containers, but I will do it on a separate thread.
