### ISSUE TITLE
Adding Docker containers

### ISSUE THREAD

**Issue by concatenize** [tabdelaal/scRNAseq_Benchmark#8]
In #7 , you mention that the pipeline looks on Dockerhub for pre-built containers. If I want to add a container for another tool such as ACTINN, how should I do that? I'm sorry to bother you, but I checked the readme files and the [singularity docs about Docker](https://singularity.lbl.gov/docs-docker), and nothing describes how to create a new Docker image on Dockerhub. Do you use Docker to create the images and Singularity to run them?

**Comment by DavyCats** [comment]
You can have a look at the documentation for [docker](https://docs.docker.com/), [dockerfiles](https://docs.docker.com/engine/reference/builder/) and [docker hub](https://docs.docker.com/docker-hub/) on how to make docker images and push them to docker hub.

Indeed we used docker to create the images and singularity to run them. You could also use singularity images, though I'm not too familiar with how those are made or distributed.

**Comment by concatenize** [comment]
Thanks! I'll do that.
